name: Greet and Assign Issue

on:
  issues:
    types:
      - opened
      - edited

jobs:
  greet-and-assign:
    runs-on: ubuntu-latest

    steps:
      - name: Greet with a comment
        uses: actions/github-script@v4
        with:
          script: |
            const issueComment = 'Hello there, thanks for creating this issue!';
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment
            });

      - name: Check for "/assign" command
        id: check-command
        uses: actions/github-script@v4
        with:
          script: |
            const { data: comments } = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const lastComment = comments[comments.length - 1];
            const assignCommand = '/assign';

            if (lastComment && lastComment.body.includes(assignCommand)) {
              return { assign: true };
            }

            return { assign: false };

      - name: Assign issue and add label
        if: steps.check-command.outputs.assign == 'true'
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [context.actor]
            });

            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['GSSoC23']
            });
