name: Greet on Issue Creation

on:
  issues:
    types:
      - opened

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Greet User
        uses: peter-evans/create-issue-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Hello there, thanks for creating this issue!"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
