name: Greet and Assign Issue

on:
  issues:
    types:
      - opened
      - edited

jobs:
  greet-and-assign:
    runs-on: ubuntu-latest

    steps:
      - name: Greet with a comment
        uses: actions/github-script@v5
        with:
          script: |
            const issueComment = `Hello there, thanks for creating this issue!`;
            const octokit = context.octokit;
            const payload = {
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment
            };
            return octokit.issues.createComment(payload);

      - name: Check for "/assign" command
        id: check-command
        uses: actions/github-script@v5
        with:
          script: |
            const octokit = context.octokit;
            const { data: comments } = await octokit.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const lastComment = comments[comments.length - 1];
            const assignCommand = '/assign';

            if (lastComment && lastComment.body.includes(assignCommand)) {
              return { assign: true };
            }

            return { assign: false };

      - name: Assign issue and add label
        if: steps.check-command.outputs.assign == 'true'
        uses: actions/github-script@v5
        with:
          script: |
            const octokit = context.octokit;
            const payload = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [context.actor]
            };

            await octokit.issues.addAssignees(payload);

            const labelPayload = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['GSSoC23']
            };

            return octokit.issues.addLabels(labelPayload);
