name: Greet, Label, and Assign Issue

on:
  issues:
    types:
      - opened
      - edited

jobs:
  greet-label-assign:
    runs-on: ubuntu-latest

    steps:
      - name: Greet with a comment
        uses: actions/github-script@v4
        with:
          script: |
            const greeting = 'Hello there, thanks for creating this issue!';
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: greeting
            });

      - name: Add label if contains "GSSoC23"
        uses: actions/github-script@v4
        with:
          script: |
            const labelName = 'GSSoC23';
            const issueContent = context.payload.issue.body;

            if (issueContent.includes(labelName)) {
              github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: [labelName]
              });
            }

      - name: Check for "/assign" command
        id: check-command
        uses: actions/github-script@v4
        with:
          script: |
            const { data: comments } = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const lastComment = comments[comments.length - 1];
            const assignCommand = '/assign';

            if (lastComment && lastComment.body.includes(assignCommand)) {
              return { assign: true };
            }

            return { assign: false };

      - name: Assign issue
        if: steps.check-command.outputs.assign == 'true'
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: [context.actor]
            });
